package compiler

import (
	"fmt"
	"strings"

	"github.com/kennguy3n/skills-library/internal/skill"
)

type clineFormatter struct{}

func (clineFormatter) Name() string            { return "cline" }
func (clineFormatter) OutputName() string      { return ".clinerules" }
func (clineFormatter) DefaultTier() skill.Tier { return skill.TierCompact }

func (clineFormatter) Format(skills []*skill.Skill, tier skill.Tier, ctx Context) string {
	var b strings.Builder
	b.WriteString("# Skills Library — Cline / OpenCode security rules\n")
	b.WriteString("# Generated by skills-check. Edit the skills/ source, not this file.\n\n")
	for _, s := range skills {
		fmt.Fprintf(&b, "## %s\n", s.Frontmatter.Title)
		for _, line := range s.Body.Always {
			fmt.Fprintf(&b, "REQUIRE: %s\n", line)
		}
		for _, line := range s.Body.Never {
			fmt.Fprintf(&b, "REJECT:  %s\n", line)
		}
		if tier != skill.TierMinimal {
			for _, line := range s.Body.KnownFalsePositives {
				fmt.Fprintf(&b, "ALLOW:   %s\n", line)
			}
		}
		b.WriteString("\n")
	}
	b.WriteString(VulnSummary(ctx))
	b.WriteString(GlossaryBlock(ctx))
	return b.String()
}
